# ============================================================
# Docker Compose Override - Development Environment
# ============================================================
# This file is automatically merged with docker-compose.yml
# when running docker-compose commands without specifying a file.
#
# Purpose: Development-specific settings
#   - Volume mounts for hot reload
#   - Debug ports
#   - Development environment variables
#   - Additional logging
#
# Usage:
#   Normal:  docker-compose up (uses both files)
#   Prod:    docker-compose -f docker-compose.yml up
# ============================================================

version: '3.8'

services:
  api:
    # Development-specific environment variables
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiKey=dev-api-key-12345
      
      # Enable detailed logging for development
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft.AspNetCore=Information
      - Logging__LogLevel__TransactionAggregationApi=Debug
      
      # Development cache settings (shorter TTL for testing)
      - Cache__DefaultTtlMinutes=5
    
    # Volume mounts for hot reload (optional)
    # Uncomment to enable live code changes without rebuild
    # volumes:
    #   - ./TransactionAggregationApi.Api:/app
    
    # Expose additional ports for debugging
    # ports:
    #   - "5000:8080"  # Alternative port mapping
    
  redis:
    # Development-specific Redis configuration
    # More verbose logging
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 128mb
      --maxmemory-policy allkeys-lru
      --loglevel notice
    
    # Expose Redis port to host for debugging tools
    ports:
      - "6379:6379"
